# Generated by Django 3.1.7 on 2021-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0002_auto_20210404_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='album',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solo',
            name='end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solo',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
