# Generated by Django 3.1.7 on 2021-04-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0003_auto_20210407_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='slug',
            field=models.SlugField(default='unknown'),
            preserve_default=False,
        ),
    ]
